import type { FlatTreeData } from "./types";

export const personalWebsiteExample: FlatTreeData = {
  items: {
    root: {
      id: "root",
      type: "branch",
      name: "Personal Website Launch",
      parentId: null,
      childOrder: [
        "Swe3U-phABu4sV7wcy6_v",
        "hvpOF4XS-A1TQtrEXvfNg",
        "oBsDGzknBld9puXCKVp4W",
        "BCL3REmg3e2CU4w7qGAyZ",
      ],
      certainty: "high",
    },
    "Swe3U-phABu4sV7wcy6_v": {
      id: "Swe3U-phABu4sV7wcy6_v",
      type: "branch",
      name: "Setup Hosting",
      parentId: "root",
      childOrder: ["st7a4uZPxx6WsChJNKpbX", "v9blgbKTf1H8YOGOH0ieR"],
      certainty: "low",
    },
    st7a4uZPxx6WsChJNKpbX: {
      id: "st7a4uZPxx6WsChJNKpbX",
      type: "leaf",
      name: "Register domain name",
      estimate: "2h",
      parentId: "Swe3U-phABu4sV7wcy6_v",
      completed: false,
    },
    v9blgbKTf1H8YOGOH0ieR: {
      id: "v9blgbKTf1H8YOGOH0ieR",
      type: "leaf",
      name: "Choose website platform",
      estimate: "3h",
      parentId: "Swe3U-phABu4sV7wcy6_v",
      completed: false,
    },
    "hvpOF4XS-A1TQtrEXvfNg": {
      id: "hvpOF4XS-A1TQtrEXvfNg",
      type: "branch",
      name: "Website Design",
      parentId: "root",
      childOrder: ["aiQotaokrgCFXKPGAYCUL", "EyHbchn0eCVV1Ltw8L3K9"],
      certainty: "high",
    },
    aiQotaokrgCFXKPGAYCUL: {
      id: "aiQotaokrgCFXKPGAYCUL",
      type: "leaf",
      name: "Design homepage",
      estimate: "2d",
      parentId: "hvpOF4XS-A1TQtrEXvfNg",
      completed: false,
    },
    EyHbchn0eCVV1Ltw8L3K9: {
      id: "EyHbchn0eCVV1Ltw8L3K9",
      type: "leaf",
      name: "Design logo",
      estimate: "3h",
      parentId: "hvpOF4XS-A1TQtrEXvfNg",
      completed: false,
    },
    oBsDGzknBld9puXCKVp4W: {
      id: "oBsDGzknBld9puXCKVp4W",
      type: "branch",
      name: "Content Creation",
      parentId: "root",
      childOrder: ["33eFpvoh0NSQjdK70C_4r", "cMsQIw5zImzbfEZA71lI8"],
      certainty: "medium",
    },
    "33eFpvoh0NSQjdK70C_4r": {
      id: "33eFpvoh0NSQjdK70C_4r",
      type: "leaf",
      name: "Write About Me content",
      estimate: "2h",
      parentId: "oBsDGzknBld9puXCKVp4W",
      completed: false,
    },
    cMsQIw5zImzbfEZA71lI8: {
      id: "cMsQIw5zImzbfEZA71lI8",
      type: "leaf",
      name: "Set up contact form",
      estimate: "5h",
      parentId: "oBsDGzknBld9puXCKVp4W",
      completed: false,
    },
    BCL3REmg3e2CU4w7qGAyZ: {
      id: "BCL3REmg3e2CU4w7qGAyZ",
      type: "branch",
      name: "Deployment",
      parentId: "root",
      childOrder: ["L-AGdzs51HJHD-Afpk7r6"],
      certainty: "medium",
    },
    "L-AGdzs51HJHD-Afpk7r6": {
      id: "L-AGdzs51HJHD-Afpk7r6",
      type: "leaf",
      name: "Deploy website",
      estimate: "2h",
      parentId: "BCL3REmg3e2CU4w7qGAyZ",
      completed: false,
    },
  },
  rootId: "root",
};
